kind: Deployment

name: config-server

replicaCount: 1

image:
  repository: shejulv088/final_config_server
  tag: v2

service:
  type: ClusterIP
  port: 8888

config: {}
secret: {}

livenessProbe:
  path: /actuator/health
  initialDelaySeconds: 60
  periodSeconds: 20

readinessProbe:
  path: /actuator/health
  initialDelaySeconds: 30
  periodSeconds: 15

resources: {}
