kind: Deployment
name: discovery-server

replicaCount: 1

image:
  repository: shejulv088/final_discovery_server
  tag: v1

service:
  type: ClusterIP
  port: 8761

config: false
secret: false

livenessProbe:
  path: /actuator/health
  initialDelaySeconds: 60
  periodSeconds: 20

readinessProbe:
  path: /actuator/health
  initialDelaySeconds: 30
  periodSeconds: 15
