name: api-gateway
replicaCount: 1
kind: Deployment

image:
  repository: shejulv088/jenkins_api_gateway
  tag: "41-ae8280b"

service:
  port: 8080

livenessProbe:
  path: /actuator/health
  initialDelaySeconds: 60
  periodSeconds: 20

readinessProbe:
  path: /actuator/health
  initialDelaySeconds: 30
  periodSeconds: 15

config:
  SPRING_CONFIG_URI: http://config-server:8888
  SPRING_PROFILES_ACTIVE: native
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka

#resources:
#  requests:
#    cpu: 50m
#    memory: 150Mi
#  limits:
#    cpu: 100m
#    memory: 200Mi

